#!/usr/bin/env bash
# =============================================================================
# alias.sh — installs addalias / addaliasall commands into the system
# Usage:
#   chmod +x alias.sh && ./alias.sh
# =============================================================================

set -e

# ---------- helpers ----------------------------------------------------------

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'

info()    { echo -e "${GREEN}[+]${NC} $*"; }
warn()    { echo -e "${YELLOW}[!]${NC} $*"; }
error()   { echo -e "${RED}[✗]${NC} $*" >&2; }

require_root() {
    if [[ $EUID -ne 0 ]]; then
        error "This script must be run as root (use sudo)."
        exit 1
    fi
}

# ---------- the two functions that will be injected --------------------------

# Text of addalias — adds an alias for the CURRENT user
ADDALIAS_FUNC='
# ---- addalias ---------------------------------------------------------------
# Usage: addalias <name> <command>
# Example: addalias ll "ls -la"
addalias() {
    if [[ $# -lt 2 ]]; then
        echo "Usage: addalias <alias_name> <command>"
        return 1
    fi

    local alias_name="$1"
    shift
    local alias_cmd="$*"

    # Validate alias name (letters, digits, dash, underscore only)
    if [[ ! "$alias_name" =~ ^[a-zA-Z_][a-zA-Z0-9_-]*$ ]]; then
        echo "Error: invalid alias name '\''$alias_name'\''"
        return 1
    fi

    # Detect the user'\''s shell rc-file
    local rc_file
    case "$SHELL" in
        */zsh)  rc_file="$HOME/.zshrc"  ;;
        */bash) rc_file="$HOME/.bashrc" ;;
        *)      rc_file="$HOME/.profile" ;;
    esac

    # Remove old definition if present
    sed -i "/^alias ${alias_name}=/d" "$rc_file" 2>/dev/null || true

    echo "alias ${alias_name}='\''${alias_cmd}'\''" >> "$rc_file"
    echo "Alias '\''${alias_name}'\'' added to ${rc_file}"
    echo "Run: source ${rc_file}   (or open a new terminal)"
}
export -f addalias 2>/dev/null || true
'

# Text of addaliasall — adds an alias for EVERY user + root
ADDALIASALL_FUNC='
# ---- addaliasall ------------------------------------------------------------
# Usage: addaliasall <name> <command>   (must be run as root / sudo)
# Example: sudo addaliasall ll "ls -la"
addaliasall() {
    if [[ $EUID -ne 0 ]]; then
        echo "Error: addaliasall must be run as root (sudo addaliasall ...)."
        return 1
    fi

    if [[ $# -lt 2 ]]; then
        echo "Usage: addaliasall <alias_name> <command>"
        return 1
    fi

    local alias_name="$1"
    shift
    local alias_cmd="$*"

    if [[ ! "$alias_name" =~ ^[a-zA-Z_][a-zA-Z0-9_-]*$ ]]; then
        echo "Error: invalid alias name '\''$alias_name'\''"
        return 1
    fi

    # --- Write to /etc/profile.d/ so every login shell picks it up ----------
    local global_file="/etc/profile.d/custom_aliases.sh"

    # Remove old definition
    if [[ -f "$global_file" ]]; then
        sed -i "/^alias ${alias_name}=/d" "$global_file"
    fi

    echo "alias ${alias_name}='\''${alias_cmd}'\''" >> "$global_file"
    chmod 644 "$global_file"

    # --- Also patch every existing user'\''s rc-file -------------------------
    while IFS=: read -r username _ uid _ _ homedir shell; do
        # Skip system accounts (uid < 1000) except root (uid 0)
        [[ "$uid" -ge 1000 || "$uid" -eq 0 ]] || continue
        [[ -d "$homedir" ]] || continue

        local rc_file
        case "$shell" in
            */zsh)  rc_file="$homedir/.zshrc"  ;;
            */bash) rc_file="$homedir/.bashrc" ;;
            *)      rc_file="$homedir/.profile" ;;
        esac

        # Create rc-file if absent
        [[ -f "$rc_file" ]] || touch "$rc_file"

        sed -i "/^alias ${alias_name}=/d" "$rc_file"
        echo "alias ${alias_name}='\''${alias_cmd}'\''" >> "$rc_file"
        echo "  -> patched: $rc_file"
    done < /etc/passwd

    echo "Alias '\''${alias_name}'\'' added globally and to all user rc-files."
}
export -f addaliasall 2>/dev/null || true
'

# ---------- installation logic -----------------------------------------------

require_root

GLOBAL_RC="/etc/bash.bashrc"        # sourced by all interactive bash sessions
PROFILE_D="/etc/profile.d/addalias.sh"

info "Installing addalias / addaliasall..."

# ---- 1. Write both functions to /etc/profile.d/addalias.sh -----------------
cat > "$PROFILE_D" <<EOF
#!/usr/bin/env bash
# Auto-generated by alias.sh — do not edit manually
${ADDALIAS_FUNC}
${ADDALIASALL_FUNC}
EOF
chmod 644 "$PROFILE_D"
info "Functions written to ${PROFILE_D}"

# ---- 2. Ensure /etc/bash.bashrc sources /etc/profile.d/ --------------------
#   (Most distros already do this, but we make sure.)
if ! grep -q "profile\.d" "$GLOBAL_RC" 2>/dev/null; then
    cat >> "$GLOBAL_RC" <<'SNIPPET'

# Source /etc/profile.d scripts for interactive shells
if [ -d /etc/profile.d ]; then
    for _f in /etc/profile.d/*.sh; do
        [ -r "$_f" ] && . "$_f"
    done
    unset _f
fi
SNIPPET
    info "Added profile.d sourcing to ${GLOBAL_RC}"
fi

# ---- 3. Patch every existing user's rc-file so it works right away ----------
info "Patching existing users' rc-files..."

while IFS=: read -r username _ uid _ _ homedir shell; do
    [[ "$uid" -ge 1000 || "$uid" -eq 0 ]] || continue
    [[ -d "$homedir" ]] || continue

    rc_file=""
    case "$shell" in
        */zsh)  rc_file="$homedir/.zshrc"  ;;
        */bash) rc_file="$homedir/.bashrc" ;;
        *)      rc_file="$homedir/.profile" ;;
    esac

    [[ -f "$rc_file" ]] || touch "$rc_file"

    # Avoid double-sourcing
    if ! grep -q "profile\.d/addalias\.sh" "$rc_file" 2>/dev/null; then
        cat >> "$rc_file" <<SNIPPET

# Load addalias / addaliasall (added by alias.sh)
[ -f /etc/profile.d/addalias.sh ] && . /etc/profile.d/addalias.sh
SNIPPET
        info "  -> patched: $rc_file (user: $username)"
    else
        warn "  -> already patched: $rc_file (user: $username)"
    fi
done < /etc/passwd

# ---------- done -------------------------------------------------------------

echo ""
info "Installation complete!"
echo ""
echo "  Usage examples:"
echo "    addalias ll 'ls -la'                   # adds alias for current user"
echo "    sudo addaliasall ll 'ls -la'           # adds alias for all users"
echo ""
echo "  Open a new terminal (or run: source ~/.bashrc) to activate."
echo ""
warn "You can now safely delete this script."
